[package]
name = "destruction-studios/loot-table"
version = "0.0.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
UniqueKey = "destruction-studios/uniquekey@1.0.4"